# Generated by Django 3.2.10 on 2022-01-24 22:15

import backend.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_add_tag_anchor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="tag description"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="verification_key",
            field=models.CharField(
                blank=True,
                default=backend.models.user._generate_verification_key,
                help_text="Designates whether this user is activated or not",
                max_length=48,
                verbose_name="is activated",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("tag_anchor", "lang_code"), name="unique_with_lang_tag"
            ),
        ),
    ]
