# Generated by Django 3.2.10 on 2022-01-25 04:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_add_graph"),
    ]

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("modified_time", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="code's name"
                    ),
                ),
                ("code", models.TextField(verbose_name="code entity")),
                (
                    "tutorial_anchor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.tutorialanchor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
