# Generated by Django 3.2.10 on 2022-01-26 04:21
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_add_execution_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphanchor",
            name="default_order",
            field=models.PositiveIntegerField(
                choices=[(100, "high"), (60, "medium"), (20, "low")],
                default=20,
                verbose_name="graph default order",
            ),
        ),
        migrations.CreateModel(
            name="OrderedGraphAnchor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        choices=[(100, "high"), (60, "medium"), (20, "low")],
                        default=20,
                        verbose_name="graph order",
                    ),
                ),
                (
                    "graph_anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.graphanchor",
                    ),
                ),
                (
                    "tutorial_anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.tutorialanchor",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("modified_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="graphanchor",
            name="tutorial_anchor",
            field=models.ManyToManyField(
                through="backend.OrderedGraphAnchor", to="backend.TutorialAnchor"
            ),
        ),
    ]
