# Generated by Django 3.2.10 on 2022-03-13 02:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_add_graph_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uploads",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("modified_time", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="")),
                ("name", models.CharField(max_length=300, verbose_name="file name")),
                ("graph_anchors", models.ManyToManyField(to="backend.GraphAnchor")),
                (
                    "tutorial_anchors",
                    models.ManyToManyField(to="backend.TutorialAnchor"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
