# Generated by Django 3.2.12 on 2022-03-21 00:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_add_uploads"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorialanchor",
            name="tags",
        ),
        migrations.AddField(
            model_name="tutorialanchor",
            name="tag_anchors",
            field=models.ManyToManyField(
                related_name="tutorial_anchors", to="backend.TagAnchor"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2022, 3, 21, 0, 24, 39, 132617, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="modified_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_anchor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="backend.taganchor",
            ),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="authors",
            field=models.ManyToManyField(
                related_name="tutorials", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="tutorial_anchor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tutorials",
                to="backend.tutorialanchor",
            ),
        ),
    ]
