# Generated by Django 3.2.12 on 2022-03-21 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_auto_20220321_0024"),
    ]

    operations = [
        migrations.RenameField(
            model_name="executionresult",
            old_name="graph",
            new_name="graph_anchor",
        ),
        migrations.RemoveField(
            model_name="graphanchor",
            name="tutorial_anchor",
        ),
        migrations.AddField(
            model_name="graphanchor",
            name="tutorial_anchors",
            field=models.ManyToManyField(
                related_name="graph_anchors",
                through="backend.OrderedGraphAnchor",
                to="backend.TutorialAnchor",
            ),
        ),
        migrations.AlterField(
            model_name="code",
            name="tutorial_anchor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="code",
                to="backend.tutorialanchor",
            ),
        ),
        migrations.AlterField(
            model_name="executionresult",
            name="code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="execution_results",
                to="backend.code",
            ),
        ),
        migrations.AlterField(
            model_name="graph",
            name="graph_anchor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="graph",
                to="backend.graphanchor",
            ),
        ),
        migrations.AlterField(
            model_name="graph",
            name="makers",
            field=models.ManyToManyField(
                related_name="graphs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="graphanchor",
            name="tags",
            field=models.ManyToManyField(
                related_name="graph_anchors", to="backend.Tag"
            ),
        ),
        migrations.AlterField(
            model_name="graphdescription",
            name="authors",
            field=models.ManyToManyField(
                related_name="graph_descriptions", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="graphdescription",
            name="graph_anchor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="graph_descriptions",
                to="backend.graphanchor",
            ),
        ),
        migrations.AlterField(
            model_name="uploads",
            name="graph_anchors",
            field=models.ManyToManyField(
                related_name="uploads", to="backend.GraphAnchor"
            ),
        ),
        migrations.AlterField(
            model_name="uploads",
            name="tutorial_anchors",
            field=models.ManyToManyField(
                related_name="uploads", to="backend.TutorialAnchor"
            ),
        ),
    ]
