# Generated by Django 3.2.12 on 2022-03-21 05:55

import backend.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_auto_20220321_0053"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="executionresult",
            name="execution result unique on code and graph",
        ),
        migrations.AlterField(
            model_name="user",
            name="verification_key",
            field=models.CharField(
                blank=True,
                default=backend.models.user._generate_verification_key,
                help_text="Designates whether this user is activated or not",
                max_length=48,
                null=True,
                verbose_name="is activated",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionresult",
            constraint=models.UniqueConstraint(
                fields=("code", "graph_anchor"),
                name="execution result unique on code and graph",
            ),
        ),
    ]
