# Generated by Django 3.2.12 on 2022-03-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_auto_20220324_0739"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (5, "administrator"),
                    (4, "editor"),
                    (3, "author"),
                    (2, "translator"),
                    (1, "visitor"),
                    (0, "reader"),
                ],
                default=0,
                verbose_name="user role",
            ),
        ),
    ]
