# Generated by Django 3.2.12 on 2022-03-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0015_change_lang_code_naming"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphanchor",
            name="url",
            field=models.SlugField(
                max_length=150, unique=True, verbose_name="graph url"
            ),
        ),
        migrations.AlterField(
            model_name="tutorialanchor",
            name="url",
            field=models.SlugField(
                max_length=150, unique=True, verbose_name="tutorial url"
            ),
        ),
    ]
