# Generated by Django 3.2.12 on 2022-03-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0016_use_slug_field_for_urls"),
    ]

    operations = []
