# Generated by Django 3.2.12 on 2022-03-30 21:22

from django.db import migrations, models
import django.utils.timezone
import uuid


def fill_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    model = apps.get_model("backend", "OrderedGraphAnchor")
    for obj in model.objects.using(db_alias).all():
        obj.uuid = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0016_use_slug_field_for_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedgraphanchor",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderedgraphanchor",
            name="modified_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="orderedgraphanchor",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, serialize=False, unique=True
            ),
        ),
        migrations.RunPython(fill_uuid, migrations.RunPython.noop),
        migrations.RemoveField(model_name="orderedgraphanchor", name="id"),
        migrations.RenameField(
            model_name="orderedgraphanchor", old_name="uuid", new_name="id"
        ),
        migrations.AlterField(
            model_name="orderedgraphanchor",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
