# Generated by Django 3.2.13 on 2022-04-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0017_add_mixins_to_ordered_graph_anchor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphanchor",
            name="default_order",
            field=models.PositiveIntegerField(
                choices=[(100, "high"), (60, "medium"), (20, "low")],
                default=20,
                verbose_name="graph default order",
            ),
        ),
        migrations.AlterField(
            model_name="orderedgraphanchor",
            name="order",
            field=models.PositiveIntegerField(
                choices=[(100, "high"), (60, "medium"), (20, "low")],
                default=20,
                verbose_name="graph order",
            ),
        ),
    ]
