# Generated by Django 3.2.13 on 2022-04-16 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0017_add_mixins_to_ordered_graph_anchor"),
    ]

    operations = []
