# Generated by Django 3.2.13 on 2022-04-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0018_fix_graph_order_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderedGraphAnchor",
            new_name="OrderedAnchorTable",
        ),
    ]
