# Generated by Django 3.2.14 on 2022-07-28 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0023_alter_executionresult_graph_anchor"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphdescription",
            name="back",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backed_by",
                to="backend.graphdescription",
            ),
        ),
        migrations.AddField(
            model_name="graphdescription",
            name="edited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="graphdescription",
            name="front",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fronted_by",
                to="backend.graphdescription",
            ),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="back",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backed_by",
                to="backend.tutorial",
            ),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="edited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="front",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fronted_by",
                to="backend.tutorial",
            ),
        ),
    ]
