# Generated by Django 3.2.14 on 2022-07-29 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0024_add_version_mixin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graphdescription",
            name="front",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="front",
        ),
        migrations.AlterField(
            model_name="graphdescription",
            name="back",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="front",
                to="backend.graphdescription",
            ),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="back",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="front",
                to="backend.tutorial",
            ),
        ),
    ]
