version: "3.9"  # optional since v1.27.0
services:
  db:
    build: .
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: bind
        source: ./postgres-data
        target: /var/lib/postgresql/data