version: "3.9"  # optional since v1.27.0
services:
  db:
    restart: on-failure
    build: ./postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: bind
        source: ./volumes/postgre-data
        target: /var/lib/postgresql/data
  redis:
    restart: on-failure
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: ./volumes/redis-data
        target: /data
